// Generated by CoffeeScript 1.3.3
var parseCookie;

parseCookie = require('connect').utils.parseCookie;

module.exports = function(store, once) {
  if (once == null) {
    once = false;
  }
  return function(agent, action, next) {
    var cookie;
    if (once && agent.session) {
      return next();
    }
    cookie = parseCookie(agent.headers.cookie);
    return store.get(cookie['connect.sid'], function(err, session) {
      agent.session = session;
      return next();
    });
  };
};
