// Generated by CoffeeScript 1.3.3

module.exports = function(agent, action, next) {
  if (action.type === "create" || action.type === "connect") {
    return next();
  }
  return agent.app.model.getSnapshot(action.docName, function(err, snapshot) {
    action.snapshot = snapshot;
    return next();
  });
};
