// Generated by CoffeeScript 1.3.3
var connectSession, proto, snapshot, utils,
  __slice = [].slice;

utils = require("connect").utils;

proto = require("./proto");

snapshot = require("./middleware/snapshot");

connectSession = require("./middleware/connectSession");

exports.createAuthorizer = function() {
  var app, auth, m, middleware, _i, _len;
  app = arguments[0], middleware = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  auth = function(agent, action) {
    agent.app = app;
    return auth.handle(agent, action);
  };
  utils.merge(auth, proto);
  auth.stack = [];
  for (_i = 0, _len = middleware.length; _i < _len; _i++) {
    m = middleware[_i];
    auth.use(m);
  }
  return auth;
};

exports.snapshot = snapshot;

exports.connectSession = connectSession;
